POST http://localhost:8080/memos
Content-Type: application/json

{
"title": "테스트",
"content": "내용"
}
PUT http://localhost:8080/memos/1
Content-Type: application/json

{
"title": "수정된 제목",
"content": "수정된 내용"
}